name: Run Azure Login with OpenID Connect
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: wsrdemo0701
  AZURE_WEBAPP_PACKAGE_PATH: DotNetCoreSqlDb/published
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 7.0.x
  WORKING_DIRECTORY: DotNetCoreSqlDb

jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
  
    - name: 'Run Azure CLI commands'
      run: |
          az account show
          az group list
          pwd
          get-childitem 
    
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.x'
        include-prerelease: true
  
    - name: Build with dotnet
      run: dotnet build "./DotNetCoreSqlDb.csproj" --configuration ${{ env.CONFIGURATION }} --no-restore
              
    - name: dotnet publish
      run: dotnet publish "${{ env.WORKING_DIRECTORY }}"  -c Release -o "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
          
    - name: dotnet install ef
      run: dotnet tool install -g dotnet-ef --version 7.0.14
    
    - name: dotnet bundle migration
      run: dotnet ef migrations bundle --runtime linux-x64 -p DotNetCoreSqlDb/DotNetCoreSqlDb.csproj -o ${{env.AZURE_WEBAPP_PACKAGE_PATH}}/migrate
  
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: .net-app
        path: ${{env.AZURE_WEBAPP_PACKAGE_PATH}}
